### PR TITLE
Added iPhone 11. Optional scaleToFit and scaleUp props.

### PR DESCRIPTION
**Pull request by tyson90**

### CODE REVIEW

**Comment by benvium** [comment]
This looks great - thank you for doing this. I'm unlikely to have a chance to try this for a while. @mattvot Are you using this component in any recent apps? Would you be able to give a try before we merge it in?

**Comment by mattvot** [comment]
I haven't used it recently, but I should be able to test this tomorrow 🤞

**Review by mattvot — APPROVED** [review]
Tested and it works for me. Some nice additions here. Thanks @tyson90! I will merge and release now.

**Comment by mattvot** [comment]
0.2.0 has been released on NPM

**Pull request merged**
